### ISSUE TITLE
Support latest Makie / GLMakie

### ISSUE THREAD

**Issue by rasmushenningsson** [JuliaGraphics/QML.jl#173]
Currently, `QML.jl` works well with `GLMakie.jl` v0.6 (and `Makie.jl` v0.17).
But not with the latest versions - `GLMakie.jl`  v0.8 (and `Makie.jl` v0.19).

The error message is "`GLScreen` not defined".
Hopefully, this is a rather small fix if you're familiar with the setup, but I'm not certain.

Later, it would also be nice to use the new Package Extensions rather than `Requires.jl` for Makie support - which among other things makes it possible to put compat bounds for Makie/GLMakie.

**Comment by ufechner7** [comment]
Very good suggestions! Makie.jl is hard to support because it is still a rapidly moving target.

**Comment by barche** [comment]
The plan is to move the Makie support into a separate package. I don't think it's a simple fix to upgrade. Having a separate package will allow us to formally set compat bounds also, currently the limits set in the examples repository are the valid ones.

**Comment by ufechner7** [comment]
As first step we could investigate the errors that happen if we use Makie 0.18 ...

**Comment by pbouffard** [comment]
Just to add a data point, and in case anyone was wondering, the Makie 0.20 beta which has some breaking changes, still suffers from this same error.

**Comment by rasmushenningsson** [comment]
@JamesWrigley also mentioned on slack that there is a Google Summer Of Code project for this:
https://julialang.org/jsoc/gsoc/gui/#qml_and_makie_integration

**Comment by rasmushenningsson** [comment]
Also see QML Roadmap with discussion here: https://github.com/orgs/JuliaGraphics/discussions/4

**Comment by rasmushenningsson** [comment]
> @JamesWrigley also mentioned on slack that there is a Google Summer Of Code project for this: https://julialang.org/jsoc/gsoc/gui/#qml_and_makie_integration

The 2024 GSOC projects have been announced (https://julialang.org/blog/2024/05/gsoc-2024-fellows/), but [QML and Makie integration](https://julialang.org/jsoc/gsoc/gui/#qml_and_makie_integration) is not included in the list.

Does this mean that there is no planned work on this at the moment?

**Comment by ufechner7** [comment]
Indeed, I don't think there is any planned work on this at the moment. Please correct me if I am wrong.

**Comment by barche** [comment]
We had no viable GSOC proposals for this topic, but it is still pretty high on my todo list for QML.jl. I can’t give a timeline though.

**Comment by rasmushenningsson** [comment]
I'm happy to hear that it's still something you want to do!
I completely understand that it's not easy to find the time.

**Comment by JamesWrigley** [comment]
> I'd like to make a PR to GLMakie at some point to indicate whether or not the `Screen` owns the window, and that should make integration even simpler.

Done: https://github.com/MakieOrg/Makie.jl/pull/4073
If anyone wants to get started on fixing the Makie integration in QML.jl, I outlined the basic steps that are necessary in the new docs in the PR.

**Comment by barche** [comment]
Great, thanks a lot for this, this looks like it will make integrating Makie support a lot easier and cleaner!

**Comment by togo65** [comment]
I really look forward to GLMakie support. As of December 14th 2024, I still get `GLScreen not defined in GLMakie`.
